<?php

function unl_nodeapi(&$node, $op)
{
	if ($op == 'prepare' && $node->menu) {
		$node->menu['expanded'] = 1;
	}
}

function unl_form_alter(&$form, $form_state, $form_id)
{
	if (substr($form_id, -10) == '_node_form') {
		$form['revision_information']['#type'] = 'hidden';
		$form['author']['#type'] = 'hidden';
		$form['comment_settings']['#type'] = 'hidden';
		
		foreach($form['menu']['parent']['#options'] as $key => $val)
		{
			//the keys we're looking for are formatted as primary-links:#
			if(strpos($key, 'primary-links') === 0)
			{				
				$unl_wdn_menu[$key] = $val;
			}
		}
		$form['menu']['parent']['#options'] = $unl_wdn_menu;
	}
}

function unl_help($path, $arg)
{
    //echo 'unl_help()' . PHP_EOL;
}

function unl_wysiwyg_plugin($editor)
{
//    echo 'unl_wysiwyg_plugin()' . PHP_EOL;
    switch ($editor) {
    case 'tinymce':
        return array(
            'unl' => array(
                'path' => drupal_get_path('module', 'unl') . '/tinymce/editor_plugin.js',
                'extensions' => array('unl' => 'UNL Extension'),
                'internal' => FALSE,
                'load' => TRUE,
                // Wysiwyg wrapper plugin AJAX callback.
                // 'callback' => url('myplugin/browse'),
                // 'icon' => drupal_get_path('module', 'mymodule') . '/myplugin/myplugin.png',
                // Might need to be set later on; after retrieving customized editor
                // layout.
                //'theme_advanced_buttons1' => array(t('Button title (optional)') => 'myplugin'),
                'buttons' => array('unl'                => 'UNL Test',
                                   'unlZenBoxBright'    => 'UNL Zen Box Bright',
                                   'unlZenBoxCool'      => 'UNL Zen Box Cool',
                                   'unlZenBoxEnergetic' => 'UNL Zen Box Energetic',
                                   'unlZenBoxSoothing'  => 'UNL Zen Box Soothing',
                                   'unlZenBoxPrimary'   => 'UNL Zen Box Primary',
                                   'unlZenBoxNeutral'   => 'UNL Zen Box Neutral',
                                   'unlZenBox'          => 'UNL Zen Box (Menu)',
                                   'unlZenTableBright'    => 'UNL Zen Table Bright',
                                   'unlZenTableCool'      => 'UNL Zen Table Cool',
                                   'unlZenTableEnergetic' => 'UNL Zen Table Energetic',
                                   'unlZenTableSoothing'  => 'UNL Zen Table Soothing',
                                   'unlZenTablePrimary'   => 'UNL Zen Table Primary',
                                   'unlZenTableNeutral'   => 'UNL Zen Table Neutral',
                                   'unlZenTableNeutral'   => 'UNL Zen Table Neutral',
                                   'unlZenTable'          => 'UNL Zen Table (Menu)',
                                   'unlCol13'   => 'UNL Layout 1/3',
                                   'unlCol22'   => 'UNL Layout 2/2',
                                   'unlCol31'   => 'UNL Layout 3/1',
                                   'unlCol112'  => 'UNL Layout 1/1/2',
                                   'unlCol121'  => 'UNL Layout 1/2/1',
                                   'unlCol211'  => 'UNL Layout 2/1/1',
                                   'unlCol1111' => 'UNL Layout 1/1/1/1',
                                   'unlLayout'  => 'UNL Layout (Menu)'
                ),
                'options' => array(
                    'doctype' => '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">'
                )
            )
        );
    }
}
