<?php

function unl_cas_enable()
{
    variable_set('user_register', 0);
}

function unl_cas_init()
{
    require_once dirname(__FILE__) . '/lib/CAS/CAS.php';
    phpCAS::client(CAS_VERSION_2_0,'login.unl.edu',443,'/cas');
    phpCAS::setNoCasServerValidation();
    
    // Force a real CAS attempt every hour or whenever the unl_sso cookie disappears.
    if ($_SESSION['unl']['last_sso_check'] < time() - 60*60 || 
        !array_key_exists('unl_sso', $_COOKIE) && phpCAS::isSessionAuthenticated())
    {
        unset($_SESSION['phpCAS']['user']);
        $_SESSION['unl']['last_sso_check'] = time();
    }
    
    $auth = FALSE;
    if (array_key_exists('unl_sso', $_COOKIE)) {
        $auth = phpCAS::checkAuthentication();
    }
    
    if ($auth) {
        $username = phpCAS::getUser();
        $user = user_load_by_name($username);
        if (!$user) {
            $user = unl_cas_import_user($username);
        }
        if ($GLOBALS['user']->uid != $user->uid) {
            $GLOBALS['user'] = $user;
            user_login_finalize();
        }
    } else if (!user_is_anonymous()) {
        $GLOBALS['user'] = drupal_anonymous_user();
        user_login_finalize();
    }
}

function unl_cas_form_alter(&$form, $form_state, $form_id)
{
    if ($form_id == 'user_login') {
        $auth = phpCAS::forceAuthentication();
    }
}

function unl_cas_user_logout($account)
{
    phpCAS::logout(array('url' => url('<front>', array('absolute' => TRUE))));
}

function unl_cas_import_user($username)
{
    $xml = @file_get_contents('http://peoplefinder.unl.edu/service.php?format=xml&uid=' . $username);
    if ($xml) {
	    $dom = DOMDocument::loadXML($xml);
	    $firstName = $dom->getElementsByTagName('givenName')->item(0)->textContent;
	    $lastName = $dom->getElementsByTagName('sn')->item(0)->textContent;
	    $email = $dom->getElementsByTagName('mail')->item(0)->textContent;
	    $displayName = $dom->getElementsByTagName('displayName')->item(0)->textContent;
    } else {
    	$email = $username . '@unl.edu';
    }
    
    $userData = array(
        'name' => $username,
        'mail' => $email,
        'status' => 1
    );
    
    $user = user_save(NULL, $userData);
    return $user;
}

function unl_cas_page_alter(&$page)
{
    $logoutUrl = url('user/logout');
    $ssoScript = <<<EOF
<script type="text/javascript">
    WDN.idm.setLogoutURL('$logoutUrl');
</script>
EOF;
    $page['page_bottom']['sso']['#markup'] = $ssoScript;
}
