<?php

/**
 * Implementation of hook_menu().
 */
function unl_migration_menu() {
  $items = array();

  // Adds UNL Migration Tool to the Content menu for admin
  $items['admin/content/unl/migration'] = array(
    'title' => 'UNL Migration Tool',
    'description' => 'Migrate a static UNL template page into Drupal.',
    'access arguments' => array('unl migration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('unl_migration'),
    'type' => MENU_LOCAL_TASK,
    'file' => 'unl_migration.php',
  );

  return $items;
}

/**
 * Implementation of hook_permission().
 */
function unl_migration_permission() {
  return array(
    'unl migration' => array(
      'title' => t('Migration'),
      'description' => t('Migrate UNL Template based sites to drupal'),
    ),
  );
}
